services:
  web:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker:/var/www/html
  php-fpm:
    build: ./docker
    volumes:
      - ./docker:/var/www/html

  postgres:

    image: postgres:13
    ports:
      - 54322:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}





      
